---
spring:
  application:
    name: ad-eureka

server:
  port: 8083

eureka:
  instance:
    hostname: localhost2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost1:8082/eureka/


  profiles: localhost2

#---
#spring:
#  profiles: localhost1
#eureka:
#  server:
#    enable-self-preservation: false
#  instance:
#    hostname: localhost1
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8081/eureka/,http://localhost2:8083/eureka/
#server:
#  port: 8082
#
#---
#
#spring:
#  profiles: localhost2
#eureka:
#  instance:
#    hostname: localhost2
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost1:8082/eureka/,http://localhost:8081/eureka/
#  server:
#    enable-self-preservation: false
#server:
#  port: 8083
#
#---